[default]
address = "0.0.0.0"
port = 8080
keep_alive = 5
ident = "Rocket"
log_level = "normal"
temp_dir = "/tmp"
cli_colors = true

[default.limits]
forms = "64 kB"
json = "842 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"

[default.shutdown]
ctrlc = true
signals = ["term", "hup"]
grace = 5
mercy = 5